[LabApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[LabApp | INFO] Loading the validate_assignment nbgrader serverextension
[LabApp | INFO] Serving notebooks from local directory: /Users/ashkan/Documents/RBRAIN_IDE_IMAGES
[LabApp | INFO] 0 active kernels
[LabApp | INFO] The Jupyter Notebook is running at:
[LabApp | INFO] http://localhost:8888/?token=58941335aeb3f567102bbcc0735eef3d207592969e03f0c5
[LabApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[LabApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=58941335aeb3f567102bbcc0735eef3d207592969e03f0c5
[LabApp | INFO] Accepting one-time-token-authenticated connection from ::1
[LabApp | WARNING] 
    "@jupyter-widgets/jupyterlab-manager@0.25.11" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab                        Extension            Package
    >=0.13.1-0 <0.14.0-0              >=0.9.0-0 <0.10.0-0  @jupyterlab/application
    >=0.13.0-0 <0.14.0-0              >=0.9.0-0 <0.10.0-0  @jupyterlab/notebook
    >=0.13.0-0 <0.14.0-0              >=0.9.0-0 <0.10.0-0  @jupyterlab/rendermime
    >=0.4.3-0 <0.5.0-0                >=0.3.0-0 <0.4.0-0   @jupyterlab/rendermime-interfaces
    
    
[LabApp | WARNING] 
    "@jupyterlab/google-drive@0.6.3" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension            Package
    >=0.13.1-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/application
    >=0.13.1-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/apputils
    >=0.13.0-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/coreutils
    >=0.13.0-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/docmanager
    >=0.13.2-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/filebrowser
    >=0.13.0-0 <0.14.0-0    >=0.10.0-0 <0.11.0-0 @jupyterlab/rendermime
    >=0.52.0-0 <0.53.0-0    >=0.49.0-0 <0.50.0-0 @jupyterlab/services
    
    
[LabApp | INFO] Build not recommended
[LabApp | WARNING] 404 GET /api/contents/pydata-book?1551929778942 (::1): No such file or directory: pydata-book
[LabApp | WARNING] No such file or directory: pydata-book
[LabApp | WARNING] 404 GET /api/contents/pydata-book?1551929778942 (::1) 2.24ms referer=http://localhost:8888/lab
[LabApp | WARNING] 404 GET /api/contents/Untitled9.ipynb?content=0&1551929778945 (::1): No such file or directory: Untitled9.ipynb
[LabApp | WARNING] No such file or directory: Untitled9.ipynb
[LabApp | WARNING] 404 GET /api/contents/Untitled9.ipynb?content=0&1551929778945 (::1) 2.23ms referer=http://localhost:8888/lab
[LabApp | INFO] interrupted
[LabApp | INFO] Rsig creator thread finished
[LabApp | CRITICAL] received signal 2, stopping
[LabApp | INFO] Shutting down 0 kernels
